#!/bin/sh

cd ~

# export GTK_THEME=Catppuccin-Mocha-Standard-Mauve-Dark
gsettings set $gnome-schema gtk-theme 'Catppuccin-Mocha-Standard-Mauve-Dark'
# gsettings set $gnome-schema icon-theme 'Your icon theme'
# gsettings set $gnome-schema cursor-theme 'Your cursor Theme'
# gsettings set $gnome-schema font-name 'Your font name'

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=Hyprland

# Wayland
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=gtk2
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

exec systemd-cat --identifier=hyprland /usr/bin/Hyprland $@
